/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Dominio.Clinica;
import Dominio.Paciente;


public class winReportes extends javax.swing.JFrame {

    private final Clinica _clinica;
    
    public winReportes(Clinica c) {
        initComponents();
        _clinica = c;
        cargarReportes();
    }
    
    public void cargarReportes(){
        lblR1.setText("El total a cobrar es: "+String.valueOf(reporte1()));
        lblR2.setText("Sesiones previstas de pacientes sin obra social :"+String.valueOf(reporte2()));
        lblR3.setText("Paciente de mayor edad: "+reporte3());
    }
    
    public int reporte1(){
        int con = 0;
        int sin = 0;
        int total = 0;
        for (Paciente p : _clinica.obtenerTodos()) {
            if(p != null){
                if(p.isObraSocial()){
                    con += p.getSesionesPrevistas();
                }else{
                    sin += p.getSesionesPrevistas();
                }
            }
        }
        total = (con * 200)+(sin * 500);
        return total;
    }
    public int reporte2(){
        int total = 0;
        for (Paciente p : _clinica.obtenerTodos()) {
            if(p != null){
                if(!p.isObraSocial()){
                    total += p.getSesionesPrevistas();
                }
            }
        }
        return total;
    }
    
    public String reporte3(){
        String aux = "";
        int edad = 0;
        for (Paciente p : _clinica.obtenerTodos()) {
            if(p != null){
                if(p.getEdad() > edad){
                    aux = p.getNombre() + p.getApellido();
                    edad = p.getEdad();
                }
            }
        }
        return aux + ", Edad: "+ edad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblR3 = new javax.swing.JLabel();
        lblR2 = new javax.swing.JLabel();
        lblR1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)
                        .addGap(0, 179, Short.MAX_VALUE))
                    .addComponent(lblR1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblR3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblR1)
                .addGap(26, 26, 26)
                .addComponent(lblR2)
                .addGap(29, 29, 29)
                .addComponent(lblR3)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblR3;
    // End of variables declaration//GEN-END:variables
}
