/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Dominio.Clinica;
import Dominio.Paciente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tom
 */
public class winTabla extends javax.swing.JFrame {

    private final Clinica _clinica;

    /**
     * Creates new form winTabla
     */
    public winTabla(Clinica c) {
        initComponents();
        _clinica = c;
        this.setLocationRelativeTo(null);

        cargarTabla(0);
        listaPacientes.setListData(_clinica.obtenerTodos());
    }

    public void cargarTabla(int parametro) {
        DefaultTableModel model = new DefaultTableModel();
        Paciente[] pacientes = _clinica.obtenerTodos();
        model.setColumnIdentifiers(new String[]{"Nombre completo", "Edad", "Obra Social", "Sesiones"});
        if (parametro == 0) {
            for (Paciente p : pacientes) {
                model.addRow(p.toArray());
            }
        } else if (parametro == 1) {
            for (Paciente p : pacientes) {
                if (p.isObraSocial() == true) {
                    model.addRow((p.toArray()));
                }
            }
        } else if (parametro == 2) {
            for (Paciente p : pacientes) {
                if (p.isObraSocial() == false) {
                    model.addRow((p.toArray()));
                }
            }
        }
        tablaPacientes.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPacientes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        txtHasta = new javax.swing.JTextField();
        txtDesde = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaPacientes);

        jScrollPane2.setViewportView(listaPacientes);

        jLabel1.setText("Ver");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los pacientes", "Con obra social", "Sin obra socia" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        if (comboBox.getSelectedIndex() == 0) {
            cargarTabla(0);
        } else if (comboBox.getSelectedIndex() == 1) {
            cargarTabla(1);
        } else if (comboBox.getSelectedIndex() == 2) {
            cargarTabla(2);
        }
    }//GEN-LAST:event_comboBoxActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int desde = 0;
        int hasta = 0;
        if (!txtDesde.getText().isEmpty() && !txtHasta.getText().isEmpty()) {
            desde = Integer.parseInt(txtDesde.getText());
            hasta = Integer.parseInt(txtHasta.getText());
            filtrarDatos(desde, hasta);
        }else{
            JOptionPane.showMessageDialog(this, "Debe inficsar el filtro", "Atencion", JOptionPane.ERROR_MESSAGE);
            cargarTabla(0);
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    public void filtrarDatos(int desde, int hasta) {
        DefaultTableModel model = new DefaultTableModel();
        Paciente[] pacientes = _clinica.obtenerTodos();
        model.setColumnIdentifiers(new String[]{"Nombre completo", "Edad", "Obra Social", "Sesiones"});

        for (Paciente p : pacientes) {
            if (p.getSesionesPrevistas() >= desde && p.getSesionesPrevistas() <= hasta) {
                model.addRow(p.toArray());
            }
        }
        tablaPacientes.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Paciente> listaPacientes;
    private javax.swing.JTable tablaPacientes;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
